Blog/blog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),
    path('', include('main.urls'))
]

Blog/main/urls.py
from django.urls import path

from main import views

urlpatterns = [
    path('', views.index, name='index'),
    path('article/<int:pk>', views.article, name='get_article'),
    path('author/<int:pk>', views.author, name='get_author'),
    path('article', views.create_article, name='create_article')
]

Blog/main/models.py
from django.db import models

# Create your models here.


class Author(models.Model):
    name = models.CharField(max_length=256)

    def __str__(self):
        return self.name


class Article(models.Model):
    title = models.CharField(max_length=256)
    content = models.TextField()
    createdAt = models.DateTimeField(auto_now_add=True)

    authors = models.ManyToManyField('Author')

    def __str__(self):
        return self.title

Blog/main/views.py
from django.http import Http404
from django.shortcuts import render, get_object_or_404

from main import models
# Create your views here.


def index(request):
    # queries are executed lazily
    latest_articles = models.Article.objects \
        .all() \
        .order_by('-createdAt')[:10]

    context = {"latest_articles": latest_articles}
    return render(request, 'main/index.html', context)


def article(request, pk):
    # try:
    #     article = models.Article.objects.get(pk=pk)
    # except:
    #     raise Http404
    article = get_object_or_404(models.Article, pk=pk)

    context = {"article": article}
    return render(request, 'main/article.html', context)


def author(request, pk):
    author = get_object_or_404(models.Author, pk=pk)

    context = {"author": author}
    return render(request, 'main/author.html', context)


def create_article(request):
    authors = models.Author.objects.all()
    context = {"authors": authors}

    if request.method == "POST":
        article_data = {
            "title": request.POST['title'],
            "content": request.POST['content'],
        }
        article = models.Article.objects.create(**article_data)
        # author = models.Author.objects.get(pk=request.POST['author'])
        # article.authors.set([author])
        author = models.Author.objects.filter(pk=request.POST['author'])
        article.authors.set(author)
        context["success"] = True

    return render(request, 'main/create_article.html', context)

Blog/templates/main/article.html
{% extends 'main/base.html' %}

    {% block content %} 
    {% include 'main/nav.html' %}
    <div class="container">
        <h1>{{ article.title }}</h1>
        <h5>Created at {{ article.createdAt }}</h5>
        <h4>
            Written By: 
            {% for author in article.authors.all %}
            <a href="{% url 'get_author' author.id %}">
            {{ author }},
            </a> 
            {% endfor %}
        </h4>
        <p style="text-align: justify;">
            {{ article.content }}
        </p>
    </div>
    {% endblock %}

Blog/templates/main/author.html
{% extends 'main/base.html' %}

    {% block content %} 
    {% include 'main/nav.html' %}
    <div class="container">
        <h1>Name: {{ author.name }}</h1>
        <h4>Articles Written</h4>
        <ul>
            {% for article in author.article_set.all %}
            <li>
                <a href="{% url 'get_article' article.id %}">
                {{ article }}
                </a>
            </li>
            {% endfor %}
        </ul>
    </div>
    {% endblock %}

Blog/templates/main/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Blog Application</title>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/materialize.min.css' %}">
    <script src="{% static 'js/materialize.min.js' %}"></script>
</head>
<body> 
    {% block content %} {% endblock %}
    {% block script %} {% endblock %}
</body>
</html>

Blog/templates/main/create_article.html
{% extends 'main/base.html' %}

    {% block content %} 
    {% include 'main/nav.html' %}
    <div class="container">
        <h1 class="center-align">Create New Article</h1>
        
        <form method="POST">
            {% csrf_token %}
            <div class="input-field col s6">
                <input type="text" name="title" placeholder="Article Title" />
                <label for="first_name">Article Title</label>
            </div>
            <div class="input-field col s12">
                <textarea id="textarea1" class="materialize-textarea" name="content" placeholder="Write content here..."></textarea>
                <label for="textarea1">Textarea</label>
            </div>
            <div class="input-field col s12">
                <select name="author">
                    <option value="" disabled selected>Choose your option</option>
                    {% for author in authors %}
                        <option value="{{ author.id }}">{{ author.name }}</option>
                    {% endfor %}
                </select>
                <label>Select Author</label>
            </div>
            <br><br>
            <button class="waves-effect waves-light btn" type="submit">Submit</button>
            <button class="waves-effect waves-light btn" type="reset">Reset</button>
            <br><br>
            {% if success %}
            <div class="chip">
                Article Submitted
                <i class="close material-icons">close</i>
            </div>
            {% endif %}
        </form>
    </div>
    {% endblock %}
    {% block script %}
    <script>
        document.addEventListener('DOMContentLoaded', function() {
            var elems = document.querySelectorAll('select');
            var instances = M.FormSelect.init(elems);
        });
    </script>
    <script>
        document.addEventListener('DOMContentLoaded', function() {
            var elems = document.querySelectorAll('.chips');
            var instances = M.Chips.init(elems, options);
        });
    </script>
    {% endblock %}

Blog/templates/main/index.html
{% extends 'main/base.html' %}

    {% block content %} 
    {% include 'main/nav.html' %}
    <div class="container">
        <h1 class="center-align">Welcome to Blog Application</h1>
        <h5>Top 10 Articles</h5>
        <ul>
            {% for article in latest_articles %}
            <li>
                <a href="{% url 'get_article' article.id %}">
                {{ article }}
                </a>
            </li>
            {% endfor %}
        </ul>
    </div>
    {% endblock %}

Blog/templates/main/nav.html
<nav>
    <div class="nav-wrapper">
        <a href="" class="brand-logo" style="padding-left: 2vw;">Blogs</a>
        <ul id="nav-mobile" class="right hide-on-med-and-down">
            <li><a href="{% url 'index' %}">Home</a></li>
            <li><a href="{% url 'create_article' %}">New Blog</a></li>
        </ul>
    </div>
</nav>